# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Conference History
    url: history
    weight: 10
  - name: Steering Committee
    url: "#steering"
    weight: 20
  - name: Diveristy and Inclusion
    url: diversity
    weight: 30
  - name: Nominations
    url: nominations
    weight: 40
  - name: ACM REP 2023
    url: https://acmrep.github.io/2023
    weight: 50
  - name: ACM EIGREP
    url: https://reproducibility.acm.org/
    weight: 60
